name: Build & Deploy Spring App

on:
  push:
    branches:
      - '**'

jobs:
  build-deploy:
    name: Build and Deploy HR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup JDk
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 21

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Give Gradle permission
        run: chmod +x ./gradlew

      - name: Run Tests
        run: ./gradlew test --stacktrace

      - name: Build Application
        run: ./gradlew build --stacktrace
